import { detectLanguage, type Detection, type Lang } from "../i18n/detect";
import { t } from "../i18n";
import { readback } from "../i18n/format";
import type { Store } from "../store/types";
import { compose, type Citation, type ToolCallRecord } from "./composer";
import { systemPrompt } from "./prompt";
import type { ChatMessage, ChatProvider } from "./provider";
import { runTool, toolSpecs } from "./tools";

const MAX_STEPS = 6;
const SCRIPT_FOR: Record<Lang, Detection["script"]> = { en: "Latn", fr: "Latn", es: "Latn", zh: "Hans", hi: "Deva", ur: "Arab", pa: "Guru", ar: "Arab" };

export type TurnEvent =
  | { type: "detected"; detection: Detection; replyLanguage: Lang }
  | { type: "tool"; name: string }
  | { type: "final"; text: string; citations: Citation[]; refused: boolean; pendingKeys: string[]; messageId: string | null; replacedSentences: number; readback: string | null };

export type TurnResult = {
  text: string;
  citations: Citation[];
  refused: boolean;
  toolCalls: ToolCallRecord[];
  detection: Detection;
  replyLanguage: Lang;
  replacedSentences: string[];
  pendingKeys: string[];
  readback: string | null;
  messageId: string | null;
};

/**
 * One user turn: detect the input language, let the model route through tools,
 * then compose (claim check + citations) before anything reaches the user.
 * The reply language can differ from the input language (speak Hindi, read English).
 * Facts heard by voice get a read-back sentence generated by code.
 */
export async function runTurn(args: {
  message: string;
  store: Store;
  provider: ChatProvider;
  onEvent?: (e: TurnEvent) => void;
  persist?: boolean;
  today?: string;
  /** Override the reply language; defaults to the detected input language. */
  replyLanguage?: Lang;
  inputMode?: "voice" | "text";
  /** Hint from speech-to-text, which already knows the spoken language. */
  inputLanguage?: Lang;
}): Promise<TurnResult> {
  const { message, store, provider, onEvent } = args;
  const profile = await store.getProfile();
  const detection: Detection = args.inputLanguage
    ? { language: args.inputLanguage, script: SCRIPT_FOR[args.inputLanguage], romanized: false, confidence: 1 }
    : detectLanguage(message, profile.language);
  const replyLanguage = args.replyLanguage ?? detection.language;
  const reply: Detection = replyLanguage === detection.language ? detection : { language: replyLanguage, script: SCRIPT_FOR[replyLanguage], romanized: false, confidence: 1 };
  onEvent?.({ type: "detected", detection, replyLanguage });

  const today = args.today ?? new Date().toISOString().slice(0, 10);
  const currentYear = Number(today.slice(0, 4));
  const hasTransactions = (await store.aggregateTransactions({})) !== null;
  const conv = await store.getConversation(detection.language);
  const messages: ChatMessage[] = [
    { role: "system", content: systemPrompt({ detection: reply, profile, hasTransactions, today, inputMode: args.inputMode ?? "text", inputLanguage: detection.language }) },
    ...conv.history.map((m) => ({ role: m.role, content: m.content }) as ChatMessage),
    { role: "user", content: message },
  ];
  const specs = toolSpecs({ hasTransactions });
  const toolCalls: ToolCallRecord[] = [];
  const pendingKeys0 = profile.pending.map((p) => p.key);
  let draft = "";

  for (let step = 0; step < MAX_STEPS; step++) {
    const res = await provider.complete({ messages, tools: specs, temperature: 0 });
    if (!res.tool_calls?.length) {
      draft = res.content ?? "";
      break;
    }
    messages.push({ role: "assistant", content: res.content ?? null, tool_calls: res.tool_calls });
    for (const call of res.tool_calls) {
      if (call.type !== "function") continue;
      onEvent?.({ type: "tool", name: call.function.name });
      let input: unknown = {};
      try { input = JSON.parse(call.function.arguments || "{}"); } catch { input = { _raw: call.function.arguments }; }
      const output = await runTool(call.function.name, input, { profile: profile.confirmed, store, inputMode: args.inputMode, currentYear, pendingKeys: pendingKeys0 });
      toolCalls.push({ tool: call.function.name, input, output });
      messages.push({ role: "tool", tool_call_id: call.id, content: JSON.stringify(output) });
    }
    if (step === MAX_STEPS - 1) {
      const last = await provider.complete({ messages: [...messages, { role: "system", content: "Answer now using only the tool results above." }] });
      draft = last.content ?? "";
    }
  }

  const composed = compose({ draft, toolCalls, userText: message, profile: profile.confirmed, language: reply.language, script: reply.script });
  const staged = toolCalls
    .filter((c) => c.tool === "update_profile")
    .flatMap((c) => (c.output as { staged?: { key: string; value: unknown }[] })?.staged ?? []);
  const pendingKeys = staged.map((s) => s.key);
  // Read-back is deterministic and in the reply language: a misheard year must be caught before it counts.
  const rb = args.inputMode === "voice" && staged.length ? readback(reply.language, staged) : null;
  const body = rb && !composed.refused ? `${composed.text}\n\n${rb}` : composed.text;
  // Language we can't reply in: answer in English and say why, rather than silently switching.
  const text = detection.unsupported && !args.replyLanguage ? `${t("en", "lang.unsupported")}\n\n${body}` : body;

  let messageId: string | null = null;
  if (args.persist !== false) {
    await store.addMessage(conv.id, { role: "user", content: message });
    messageId = await store.addMessage(conv.id, { role: "assistant", content: text, citations: composed.citations }, toolCalls);
  }

  onEvent?.({ type: "final", text, citations: composed.citations, refused: composed.refused, pendingKeys, messageId, replacedSentences: composed.replacedSentences.length, readback: rb });
  return { ...composed, text, toolCalls, detection, replyLanguage: reply.language, pendingKeys, readback: rb, messageId };
}
